name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  swift-test:
    runs-on: macos-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run Swift tests
        run: swift test

      - name: Build DocC documentation
        run: ./GeneratingDocumentationSite
